name: omran
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^15.0.0
  workmanager: ^0.5.2
  rxdart: ^0.27.7
  flutter_timezone: ^1.0.7
  intl: ^0.17.0
  uuid: ^3.0.4
  image_picker: ^0.8.4
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  shared_preferences: ^2.0.10
  sqflite: ^2.2.8
  path_provider: ^2.0.2
  local_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/